---
neutron_logging_debug: "{{ openstack_logging_debug }}"
neutron_service_plugins: ""

neutron_openvswitch_agent_domua_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-neutron-openvswitch-agent"
neutron_openvswitch_agent_domua_tag: "{{ openstack_release }}"
neutron_openvswitch_agent_domua_image_full: "{{ neutron_openvswitch_agent_domua_image }}:{{ neutron_openvswitch_agent_domua_tag }}"


neutron_services:
  neutron-openvswitch-agent-domua:
    container_name: "neutron_openvswitch_agent_domua"
    image: "{{ neutron_openvswitch_agent_domua_image_full }}"
    privileged: True
    host_in_groups: >-
      {{
      inventory_hostname in groups['compute']
      }}
    volumes:
      - "{{ node_config_directory }}/neutron-openvswitch-agent-domua/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run:/run:shared"
      - "kolla_logs:/var/log/kolla/"

